version: "3.7"

x-env_file: &env_file
  env_file:
    - ./.env

services:
  backend:
    <<: *env_file
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host=0.0.0.0 --port 5000
    tty: true
    stdin_open: true
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./app/:/app
    depends_on:
      - worker

  rabbitmq:
    <<: *env_file
    image: rabbitmq:3.8.9-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    hostname: redis
    image: redis:alpine
    ports:
      - 6379:6379

  worker:
    <<: *env_file
    build: .
    command: celery -A app.worker.tasks worker -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - redis