version: "3.7"

x-env_file: &env_file
  env_file:
    - ./.env

services:
  backend:
    <<: *env_file
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host=0.0.0.0 --port 8000
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./app/:/app